# Generated by Django 3.0.7 on 2020-08-12 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=200, unique='True', verbose_name='Province')),
            ],
            options={
                'ordering': ['province'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipe', models.CharField(default='', max_length=200, verbose_name='Municipe')),
                ('id_province', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='id_provincia', to='api.Provincia', verbose_name='Province')),
            ],
            options={
                'ordering': ['id_province', 'municipe'],
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbood', models.CharField(default='', max_length=200, verbose_name='Neighbood')),
                ('street', models.CharField(default='', max_length=200, verbose_name='Street')),
                ('id_municipe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Municipio', verbose_name='Municipe')),
            ],
            options={
                'ordering': ['neighbood'],
            },
        ),
    ]
