# Generated by Django 3.0.7 on 2020-11-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='capital',
            field=models.CharField(default='', max_length=200, unique='True', verbose_name='Capital'),
        ),
    ]
